### ISSUE TITLE
Can't find latest version of mint

### ISSUE THREAD

**Issue by bp313** [swift-on-server/developing-with-swift-in-visual-studio-code-sample#1]
Hi! Running through the steps from the [tutorial](https://swiftonserver.com/developing-with-swift-in-visual-studio-code/), the 'Finding latest version of mint' seems to be hanging.

```shell
 => [server-dev dev_container_auto_added_stage_label 5/8] RUN cd &&      770.1s
 => => # [86/89] Emitting module Mint                                          
 => => # [87/89] Compiling Mint main.swift                                     
 => => # [89/91] Wrapping AST for Mint for debugging                           
 => => # [90/91] Linking mint                                                  
 => => # Build complete! (3.43s)                                               
 => => # 🌱 Finding latest version of mint                                      
```

I presume this is not normal. Any ideas on a fix? I'm a total Docker newb.

**Comment by Joannis** [comment]
Hey @bp313 , thanks for reaching out! That's definitely not supposed to happen. While it is normal that `mint` takes a while on the first launch, this is abnormal. I've pushed a PR with a simpler dev container in #2, since we don't need most complexity for this tutorial.

**Comment by Joannis** [comment]
Merged in main!

**Comment by Joannis** [comment]
Let me know if the issue persists with the new sample code

**Comment by bp313** [comment]
That worked, thank you!

![Swift-Containers-VSCode screenshot](https://github.com/swift-on-server/developing-with-swift-in-visual-studio-code-sample/assets/330309/61cd527d-7dd9-4512-9727-16465bb0b18a)

**Comment by Joannis** [comment]
Quick heads up @bp313 , this is a recent issue with Mint it seems. Our internal dev containers are facing the same issue as of this week.
